/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.quasar.IULChef.presentationLayer;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

import org.quasar.IULChef.businessLayer.Empregado;
import org.quasar.IULChef.businessLayer.Entidade;
import org.quasar.IULChef.businessLayer.Restaurante;
import org.quasar.IULChef.businessLayer.TipoEmpregado;
import org.quasar.IULChef.persistenceLayer.Database;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author terroma
 */
public class IULChef_Login extends JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form IULChef_Login
	 */
	public IULChef_Login() {
		initComponents();
		setTitle("Login");
		setLocation(550, 350);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		addWindowListener(new WindowAdapter() {
			public void windowClosing(WindowEvent e){
				System.out.println("Desconectar BD");
                Database.close();
            }
		});
		
		jPanel1 = new javax.swing.JPanel();
		jLabelNc = new javax.swing.JLabel();
		jTextFieldNc = new javax.swing.JTextField();
		jButtonLogin = new javax.swing.JButton();
		jButtonLogin.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {

				for (Entidade e : Empregado.allInstances()) {
					if (e.nc().equals(Integer.parseInt(jTextFieldNc.getText()))) {
						empregado = ((Empregado) e);
					}
				}
				
				for (Entidade r : Restaurante.allInstances()) {
					if (r.nome().equals(NOME_RESTAURANTE)) {
						restaurante = ((Restaurante) r);
					}else{
						restaurante = new Restaurante("rua", 934587994, NOME_RESTAURANTE);
					}
				}

				openCorrectWindow();
			}

			private void openCorrectWindow() {
				switch(empregado.tipo()) {
				case Cozinheiro:
					
					dispose();
					
					new IULChef_Cozinheiro(empregado, restaurante);
					
					break;
				case Gerente:
					
					dispose();
					
					new IULChef_Gerente(empregado, restaurante);
					
					break;
				case EmpregadoMesa:
					
					dispose();
					
					new IULChef_EmpregadoMesa(empregado, restaurante);
					
					break;
				default:
					break;
				}
			}
		});

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabelNc.setText("Nc:");

		jButtonLogin.setText("Login");
		jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonLoginActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(19, 19, 19)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jButtonLogin,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabelNc)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jTextFieldNc,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				100,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(15, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(10, 10, 10)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabelNc)
														.addComponent(
																jTextFieldNc,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												28, Short.MAX_VALUE)
										.addComponent(
												jButtonLogin,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												64,
												javax.swing.GroupLayout.PREFERRED_SIZE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(12, Short.MAX_VALUE)));

		pack();
		setVisible(true);
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonLoginActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButtonLoginActionPerformed
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private JButton jButtonLogin;
	private JLabel jLabelNc;
	private JPanel jPanel1;
	private JTextField jTextFieldNc;
	private Empregado empregado;
	private static final String NOME_RESTAURANTE = "Pizzaria Mr. Pizza";
	private Restaurante restaurante;
	// End of variables declaration//GEN-END:variables
}
