/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.quasar.IULChef.presentationLayer;

import java.nio.channels.NetworkChannel;
import java.util.Calendar;

import org.quasar.IULChef.businessLayer.CalendarDate;
import org.quasar.IULChef.businessLayer.Cliente;
import org.quasar.IULChef.businessLayer.Empregado;
import org.quasar.IULChef.businessLayer.Entidade;
import org.quasar.IULChef.businessLayer.Fatura;
import org.quasar.IULChef.businessLayer.Mesa;
import org.quasar.IULChef.businessLayer.Restaurante;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author terroma
 */
public class IULChef_PassarFatura extends javax.swing.JDialog {

    private Empregado empregado;
	private Restaurante restaurante;
	private Mesa mesa;
	/**
     * Creates new form IULChef_PassarFatura
     */
    public IULChef_PassarFatura(Empregado empregado, Restaurante restaurante) {
    	this.empregado = empregado;
    	this.restaurante = restaurante;
        initComponents();
        preencheComboBox();
        setModalityType(DEFAULT_MODALITY_TYPE);
        setLocation(450, 350);
    }


	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCliente = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelNc = new javax.swing.JLabel();
        jLabelMesa = new javax.swing.JLabel();
        jLabelNrMesa = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldNc = new javax.swing.JTextField();
        jButtonPassarFatura = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jComboBoxNumeroMesa = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelCliente.setText("Cliente");

        jLabelNome.setText("Nome:");

        jLabelNc.setText("Nc:");

        jLabelMesa.setText("Mesa");

        jLabelNrMesa.setText("Nr:");

        jButtonPassarFatura.setText("Passar Fatura");
        jButtonPassarFatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPassarFaturaActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        
        JLabel lblMorada = new JLabel("Morada:");
        
        textField = new JTextField();
        textField.setColumns(10);


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(72)
        					.addComponent(jLabelCliente))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(16)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabelNrMesa)
        							.addGap(18)
        							.addComponent(jComboBoxNumeroMesa, 0, 153, Short.MAX_VALUE))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        									.addGroup(jPanel1Layout.createSequentialGroup()
        										.addComponent(jLabelNc)
        										.addGap(47))
        									.addGroup(jPanel1Layout.createSequentialGroup()
        										.addComponent(lblMorada)
        										.addGap(18)))
        								.addComponent(jLabelNome))
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jTextFieldNc, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        								.addComponent(textField, GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        								.addComponent(jLabelMesa)
        								.addComponent(jTextFieldNome, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))))
        				.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jButtonPassarFatura, GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
        				.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        					.addContainerGap(125, Short.MAX_VALUE)
        					.addComponent(jButtonVoltar)))
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabelCliente)
        			.addGap(12)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTextFieldNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabelNome))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTextFieldNc, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabelNc))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblMorada))
        			.addPreferredGap(ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
        			.addComponent(jLabelMesa)
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jComboBoxNumeroMesa, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabelNrMesa))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jButtonPassarFatura, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jButtonVoltar)
        			.addGap(60))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 307, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(58, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
	private void preencheComboBox() {
		int mesa = 0;
    	for (Mesa m : Mesa.allInstances()) {
			mesa = m.numero();
			jComboBoxNumeroMesa.addItem(mesa);
		}
	}
    
    private void getSelectedMesa(){
    	
    	for (Mesa m : Mesa.allInstances()) {
			if(m.numero().toString() == jComboBoxNumeroMesa.getSelectedItem().toString());
				mesa = m;
		}
    }
    
    private Integer criaNumeroFatura(){
    	Integer randomNum = 1 + (int)(Math.random()*1000);
    	for (Fatura f : Fatura.allInstances()) {
			if(randomNum!=f.numero()){
				return randomNum;
			}else{
				criaNumeroFatura();
			}
		}
		return randomNum;
    }
    
    private Cliente verificaCliente(){
    	for (Entidade cliente : Cliente.allInstances()) {
			if(cliente.nc().equals(Integer.parseInt(jTextFieldNc.getText()))){
				return (Cliente) cliente;
			}else{
				Cliente novoCliente = new Cliente(textField.getText(), Integer.parseInt(jTextFieldNc.getText()), jTextFieldNome.getText());
				return novoCliente;
			}
		}
		return null;
    }
    
    private void jButtonPassarFaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPassarFaturaActionPerformed
    	int quantiFaturas = Fatura.allInstances().size();
    	getSelectedMesa();
    	empregado.PassaFatura(verificaCliente(), mesa, new CalendarDate(Calendar.DAY_OF_MONTH,Calendar.MONTH, Calendar.YEAR), criaNumeroFatura());
    	if(Fatura.allInstances().size()>quantiFaturas){
    		JOptionPane.showMessageDialog(this, "Fatura passada com susseco!");
    	}else{
    		JOptionPane.showMessageDialog(this, "Ocorreu um erro!");
    	}
    }//GEN-LAST:event_jButtonPassarFaturaActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPassarFatura;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JComboBox jComboBoxNumeroMesa;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelMesa;
    private javax.swing.JLabel jLabelNc;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNrMesa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldNc;
    private javax.swing.JTextField jTextFieldNome;
    private JTextField textField;
}
