/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.quasar.IULChef.presentationLayer;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.WindowConstants;

import org.quasar.IULChef.businessLayer.Empregado;
import org.quasar.IULChef.businessLayer.Restaurante;
import org.quasar.IULChef.persistenceLayer.Database;

/**
 *
 * @author terroma
 */
public class IULChef_Gerente extends javax.swing.JFrame {

    private Empregado empregado;
	private Restaurante restaurante;
	/**
     * Creates new form IULChef_Gerente
     * @param restaurante 
     * @param empregado 
     */
    public IULChef_Gerente(Empregado empregado, Restaurante restaurante) {
    	this.empregado = empregado;
    	this.restaurante = restaurante;
        initComponents();
        setTitle("Gerente");
        setLocation(550, 350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	addWindowListener(new WindowAdapter() {
			public void windowClosed(WindowEvent e) {
				Database.close();
				new IULChef_Login();
			}
		});
    	
        jPanel1 = new javax.swing.JPanel();
        jButtonDespedir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonContratar = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();

        jButtonDespedir.setText("Despedir");
        jButtonDespedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDespedirActionPerformed(evt);
            }
        });

        jButton1.setText("Comprar Ingrediente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonContratar.setText("Contratar Empregado");
        jButtonContratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContratarActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Logout");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonContratar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jButtonDespedir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVoltar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonDespedir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonContratar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jButtonVoltar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		pack();
		setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDespedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDespedirActionPerformed
        janelaDespedir = new IULChef_Despedir(empregado,restaurante);
        janelaDespedir.setVisible(true);
    }//GEN-LAST:event_jButtonDespedirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        janelaComprarIngrediente = new IULChef_ComprarIngrediente(empregado,restaurante);
        janelaComprarIngrediente.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonContratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContratarActionPerformed
        janelaContratar = new IULChef_ContratarEmpregado(empregado,restaurante);
        janelaContratar.setVisible(true);
    }//GEN-LAST:event_jButtonContratarActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonContratar;
    private javax.swing.JButton jButtonDespedir;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JPanel jPanel1;
    private IULChef_Despedir janelaDespedir;
    private IULChef_ComprarIngrediente janelaComprarIngrediente;
    private IULChef_ContratarEmpregado janelaContratar;
    // End of variables declaration//GEN-END:variables
}
