/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.quasar.IULChef.presentationLayer;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;

import org.quasar.IULChef.businessLayer.Entidade;
import org.quasar.IULChef.businessLayer.Produto;
import org.quasar.IULChef.businessLayer.ProdutoComposto;
import org.quasar.IULChef.businessLayer.ProdutoSimples;
import org.quasar.IULChef.businessLayer.Restaurante;

/**
 *
 * @author terroma
 */
public class IULChef_NovoProdutoComposto extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form IULChef_EliminarDevolucoes
	 * 
	 * @param iulChef_Cozinheiro
	 */
	public IULChef_NovoProdutoComposto() {
		initComponents();
		setTitle("Novo Produto Composto");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabelNome = new javax.swing.JLabel();
		jLabelTipo = new javax.swing.JLabel();
		jLabelUnidade = new javax.swing.JLabel();
		jLabelPrecoVenda = new javax.swing.JLabel();
		jLabelQuantidade = new javax.swing.JLabel();
		jLabelIngredientes = new javax.swing.JLabel();
		jLabelQuantidadeIngredientes = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jListIngredientes = new javax.swing.JList();
		jScrollPane2 = new javax.swing.JScrollPane();
		jListIngredientesQuantidade = new javax.swing.JList();
		jTextFieldNome = new javax.swing.JTextField();
		TipoProdutoComposto = new javax.swing.JComboBox();
		jComboBoxUnidade = new javax.swing.JComboBox();
		jTextFieldPreco = new javax.swing.JTextField();
		jTextFieldQuantidade = new javax.swing.JTextField();
		jComboBoxGrupoProdutoComposto = new javax.swing.JComboBox();
		jButtonNovoProdutoComposto = new javax.swing.JButton();
		jButtonVoltar = new javax.swing.JButton();

		jLabelNome.setText("Nome:");

		jLabelTipo.setText("Tipo:");

		jLabelUnidade.setText("Unidade:");

		jLabelPrecoVenda.setText("Preço:");

		jLabelQuantidade.setText("Quantidade:");

		jLabelIngredientes.setText("Ingredientes:");

		jLabelQuantidadeIngredientes.setText("Quantidades:");

		jLabel1.setText("Grupo:");
		
		ArrayList<String> l = new ArrayList<String>();
		for (Entidade r : Restaurante.allInstances()) {
			for (Produto p : ((Restaurante) r).produtos()) {
				l.add(p.nome());
			}
		}

		jListIngredientes.setModel(new javax.swing.AbstractListModel() {

			// for (ProdutoSimples ing : listaIngredientes) {
			//
			// }
			Object[] strings = l.toArray();

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(jListIngredientes);

		jListIngredientesQuantidade
				.setModel(new javax.swing.AbstractListModel() {
					String[] strings = { "Item 1", "Item 2", "Item 3",
							"Item 4", "Item 5" };

					public int getSize() {
						return strings.length;
					}

					public Object getElementAt(int i) {
						return strings[i];
					}
				});
		jScrollPane2.setViewportView(jListIngredientesQuantidade);

		TipoProdutoComposto.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		TipoProdutoComposto
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						TipoProdutoCompostoActionPerformed(evt);
					}
				});

		jComboBoxUnidade.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		jComboBoxUnidade.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBoxUnidadeActionPerformed(evt);
			}
		});

		jComboBoxGrupoProdutoComposto
				.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
						"Item 1", "Item 2", "Item 3", "Item 4" }));
		jComboBoxGrupoProdutoComposto
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jComboBoxGrupoProdutoCompostoActionPerformed(evt);
					}
				});

		jButtonNovoProdutoComposto.setText("Novo Produto Composto");
		jButtonNovoProdutoComposto
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonNovoProdutoCompostoActionPerformed(evt);
					}
				});

		jButtonVoltar.setText("Voltar");
		jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonVoltarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabelNome)
																						.addComponent(
																								jLabelTipo)
																						.addComponent(
																								jLabelUnidade))
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jComboBoxUnidade,
																								0,
																								122,
																								Short.MAX_VALUE)
																						.addComponent(
																								TipoProdutoComposto,
																								0,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextFieldNome))
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel1)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												jComboBoxGrupoProdutoComposto,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												125,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabelPrecoVenda)
																										.addGap(24,
																												24,
																												24)
																										.addComponent(
																												jTextFieldPreco))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabelQuantidade)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												jTextFieldQuantidade)))
																		.addGap(24,
																				24,
																				24))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(0,
																												0,
																												Short.MAX_VALUE)
																										.addComponent(
																												jButtonVoltar))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabelIngredientes)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												jScrollPane1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												93,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(26,
																												26,
																												26)
																										.addComponent(
																												jLabelQuantidadeIngredientes)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												jScrollPane2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												94,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								jButtonNovoProdutoComposto,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))
																		.addGap(30,
																				30,
																				30)))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabelNome)
														.addComponent(
																jLabelPrecoVenda)
														.addComponent(
																jTextFieldNome,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextFieldPreco,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(6, 6, 6)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabelTipo)
														.addComponent(
																jLabelQuantidade)
														.addComponent(
																TipoProdutoComposto,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextFieldQuantidade,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jLabel1)
																		.addComponent(
																				jComboBoxUnidade,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jComboBoxGrupoProdutoComposto,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jLabelUnidade))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jLabelQuantidadeIngredientes)
														.addComponent(
																jLabelIngredientes)
														.addComponent(
																jScrollPane2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																0,
																Short.MAX_VALUE)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																92,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jButtonNovoProdutoComposto,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												79,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButtonVoltar)
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 6, Short.MAX_VALUE)));

		setModalityType(DEFAULT_MODALITY_TYPE);

		pack();
		setVisible(true);
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonNovoProdutoCompostoActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonNovoProdutoCompostoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButtonNovoProdutoCompostoActionPerformed

	private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonVoltarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButtonVoltarActionPerformed

	private void TipoProdutoCompostoActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TipoProdutoCompostoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TipoProdutoCompostoActionPerformed

	private void jComboBoxUnidadeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxUnidadeActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBoxUnidadeActionPerformed

	private void jComboBoxGrupoProdutoCompostoActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxGrupoProdutoCompostoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBoxGrupoProdutoCompostoActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox TipoProdutoComposto;
	private javax.swing.JButton jButtonNovoProdutoComposto;
	private javax.swing.JButton jButtonVoltar;
	private javax.swing.JComboBox jComboBoxGrupoProdutoComposto;
	private javax.swing.JComboBox jComboBoxUnidade;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabelIngredientes;
	private javax.swing.JLabel jLabelNome;
	private javax.swing.JLabel jLabelPrecoVenda;
	private javax.swing.JLabel jLabelQuantidade;
	private javax.swing.JLabel jLabelQuantidadeIngredientes;
	private javax.swing.JLabel jLabelTipo;
	private javax.swing.JLabel jLabelUnidade;
	private javax.swing.JList jListIngredientes;
	private javax.swing.JList jListIngredientesQuantidade;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextField jTextFieldNome;
	private javax.swing.JTextField jTextFieldPreco;
	private javax.swing.JTextField jTextFieldQuantidade;
	// End of variables declaration//GEN-END:variables
}
