/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.quasar.IULChef.presentationLayer;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Set;


import javax.swing.AbstractListModel;
import javax.swing.DefaultComboBoxModel;

import org.quasar.IULChef.businessLayer.Composicao;
import org.quasar.IULChef.businessLayer.Entidade;
import org.quasar.IULChef.businessLayer.GrupoProdutoComposto;
import org.quasar.IULChef.businessLayer.Produto;
import org.quasar.IULChef.businessLayer.ProdutoComposto;
import org.quasar.IULChef.businessLayer.ProdutoSimples;
import org.quasar.IULChef.businessLayer.Restaurante;
import org.quasar.IULChef.businessLayer.TipoProduto;
import org.quasar.IULChef.businessLayer.Unidade;
import org.quasar.IULChef.persistenceLayer.Database;

import javax.swing.DefaultListModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import javax.swing.WindowConstants;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JTextField;

/**
 *
 * @author terroma
 */
public class IULChef_NovoProdutoComposto extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private IULChef_Cozinheiro iulChef_Cozinheiro;

	/**
	 * Creates new form IULChef_EliminarDevolucoes
	 * 
	 * @param iulChef_Cozinheiro
	 * 
	 * @param iulChef_Cozinheiro
	 */
	public IULChef_NovoProdutoComposto(IULChef_Cozinheiro iulChef_Cozinheiro) {
		this.iulChef_Cozinheiro = iulChef_Cozinheiro;
		initComponents();
		setTitle("Novo Produto Composto");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		
		jPanel1 = new javax.swing.JPanel();
		jLabelNome = new javax.swing.JLabel();
		jLabelTipo = new javax.swing.JLabel();
		jLabelUnidade = new javax.swing.JLabel();
		jLabelPrecoVenda = new javax.swing.JLabel();
		jLabelQuantidade = new javax.swing.JLabel();
		jLabelIngredientes = new javax.swing.JLabel();
		jLabelQuantidadeIngredientes = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jListIngredientes = new javax.swing.JList();
		jScrollPane2 = new javax.swing.JScrollPane();
		jListIngredientesQuantidade = new javax.swing.JList();
		jTextFieldNome = new javax.swing.JTextField();
		jComboTipoProdutoComposto = new javax.swing.JComboBox();
		jComboBoxUnidade = new javax.swing.JComboBox();
		jTextFieldPreco = new javax.swing.JTextField();
		jTextFieldQuantidade = new javax.swing.JTextField();
		jComboBoxGrupoProdutoComposto = new javax.swing.JComboBox();
		jButtonNovoProdutoComposto = new javax.swing.JButton();
		jButtonVoltar = new javax.swing.JButton();

		jLabelNome.setText("Nome:");

		jLabelTipo.setText("Tipo:");

		jLabelUnidade.setText("Unidade:");

		jLabelPrecoVenda.setText("Preço:");

		jLabelQuantidade.setText("Quantidade:");

		jLabelIngredientes.setText("Ingredientes:");

		jLabelQuantidadeIngredientes.setText("Quantidade:");

		jLabel1.setText("Grupo:");

		 l = new ArrayList<String>();
		for (Entidade r : Restaurante.allInstances()) {
			for (Produto p : ((Restaurante) r).produtos()) {
				l.add(p.nome());
			}
		}

		// DefaultListModel model2 = new DefaultListModel();
		// jListIngredientes.setModel(model2);

		jListIngredientes.setModel(new javax.swing.AbstractListModel() {

			Object[] strings = l.toArray();

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});

		jScrollPane1.setViewportView(jListIngredientes);

		 model = new DefaultListModel();

		jListIngredientesQuantidade.setModel(model);

		// jListIngredientesQuantidade
		// .setModel(new AbstractListModel() {
		// String[] strings = { "Item 1", "Item 2", "Item 3",
		// "Item 4", "Item 5" };
		//
		// public int getSize() {
		// return strings.length;
		// }
		//
		// public Object getElementAt(int i) {
		// return strings[i];
		// }
		// });

		jScrollPane2.setViewportView(jListIngredientesQuantidade);

		jComboTipoProdutoComposto.setModel(new DefaultComboBoxModel<Object>(
				TipoProduto.values()));

		jComboTipoProdutoComposto
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						TipoProdutoCompostoActionPerformed(evt);
					}
				});

		jComboBoxUnidade.setModel(new DefaultComboBoxModel<Object>(Unidade
				.values()));

		jComboBoxUnidade.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBoxUnidadeActionPerformed(evt);
			}
		});

		jComboBoxGrupoProdutoComposto
				.setModel(new DefaultComboBoxModel<Object>(GrupoProdutoComposto
						.values()));

		jComboBoxGrupoProdutoComposto
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jComboBoxGrupoProdutoCompostoActionPerformed(evt);
					}
				});

		jButtonNovoProdutoComposto.setText("Novo Produto Composto");
		jButtonNovoProdutoComposto
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButtonNovoProdutoCompostoActionPerformed(evt);
					}
				});

		jButtonVoltar.setText("Voltar");
		jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonVoltarActionPerformed(evt);
			}
		});

		JButton btnEscolherIngrediente = new JButton("Escolher");
		btnEscolherIngrediente.addMouseListener(new MouseAdapter() {
			@Override
			public void mouseClicked(MouseEvent arg0) {

				if (!jListIngredientes.isSelectionEmpty()
						&& jTextFieldQuantidade.getText() != "0"
						&& jTextFieldQuantidade.getText() != "") {

					model.addElement("[" + jListIngredientes.getSelectedValue()
							+ ", " + jTextFieldQuantidade.getText() + "]");

					l.remove(jListIngredientes.getSelectedIndex());

					jListIngredientes
							.setModel(new javax.swing.AbstractListModel() {

								Object[] strings = l.toArray();

								public int getSize() {
									return strings.length;
								}

								public Object getElementAt(int i) {
									return strings[i];
								}
							});

					jLabelQuantidadeIngredientes.setText("");
				}
			}
		});

		btnEscolherIngrediente.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
			}
		});

		txtQtdComposto = new JTextField();
		txtQtdComposto.setColumns(10);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								Alignment.LEADING)
																						.addComponent(
																								jLabelNome)
																						.addComponent(
																								jLabelTipo)
																						.addComponent(
																								jLabelUnidade))
																		.addGap(18)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								Alignment.LEADING,
																								false)
																						.addComponent(
																								jComboBoxUnidade,
																								0,
																								122,
																								Short.MAX_VALUE)
																						.addComponent(
																								jComboTipoProdutoComposto,
																								0,
																								GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextFieldNome))
																		.addGap(18)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								Alignment.TRAILING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel1)
																										.addPreferredGap(
																												ComponentPlacement.RELATED,
																												13,
																												Short.MAX_VALUE)
																										.addComponent(
																												jComboBoxGrupoProdutoComposto,
																												GroupLayout.PREFERRED_SIZE,
																												125,
																												GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																Alignment.LEADING)
																														.addComponent(
																																jLabelQuantidade)
																														.addComponent(
																																jLabelPrecoVenda))
																										.addPreferredGap(
																												ComponentPlacement.RELATED)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																Alignment.LEADING,
																																false)
																														.addComponent(
																																jTextFieldPreco,
																																107,
																																107,
																																Short.MAX_VALUE)
																														.addComponent(
																																txtQtdComposto))))
																		.addGap(24))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								Alignment.TRAILING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(0,
																												305,
																												Short.MAX_VALUE)
																										.addComponent(
																												jButtonVoltar))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabelIngredientes)
																										.addPreferredGap(
																												ComponentPlacement.UNRELATED)
																										.addComponent(
																												jScrollPane1,
																												GroupLayout.PREFERRED_SIZE,
																												93,
																												GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												ComponentPlacement.RELATED)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																Alignment.LEADING)
																														.addComponent(
																																jLabelQuantidadeIngredientes)
																														.addComponent(
																																jTextFieldQuantidade,
																																GroupLayout.DEFAULT_SIZE,
																																92,
																																Short.MAX_VALUE)
																														.addComponent(
																																btnEscolherIngrediente,
																																GroupLayout.DEFAULT_SIZE,
																																92,
																																Short.MAX_VALUE))
																										.addPreferredGap(
																												ComponentPlacement.RELATED)
																										.addComponent(
																												jScrollPane2,
																												GroupLayout.PREFERRED_SIZE,
																												94,
																												GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								jButtonNovoProdutoComposto,
																								GroupLayout.DEFAULT_SIZE,
																								366,
																								Short.MAX_VALUE))
																		.addGap(30)))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																jLabelNome)
														.addComponent(
																jTextFieldNome,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextFieldPreco,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jLabelPrecoVenda))
										.addGap(6)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																Alignment.BASELINE)
														.addComponent(
																jLabelTipo)
														.addComponent(
																jLabelQuantidade)
														.addComponent(
																jComboTipoProdutoComposto,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE)
														.addComponent(
																txtQtdComposto,
																GroupLayout.PREFERRED_SIZE,
																GroupLayout.DEFAULT_SIZE,
																GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				Alignment.BASELINE)
																		.addComponent(
																				jLabel1)
																		.addComponent(
																				jComboBoxUnidade,
																				GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jComboBoxGrupoProdutoComposto,
																				GroupLayout.PREFERRED_SIZE,
																				GroupLayout.DEFAULT_SIZE,
																				GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jLabelUnidade))
										.addPreferredGap(
												ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																Alignment.LEADING,
																false)
														.addComponent(
																jLabelIngredientes)
														.addComponent(
																jScrollPane2,
																GroupLayout.PREFERRED_SIZE,
																0,
																Short.MAX_VALUE)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				Alignment.BASELINE)
																		.addComponent(
																				jScrollPane1,
																				GroupLayout.PREFERRED_SIZE,
																				92,
																				GroupLayout.PREFERRED_SIZE)
																		.addGroup(
																				jPanel1Layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabelQuantidadeIngredientes)
																						.addPreferredGap(
																								ComponentPlacement.RELATED)
																						.addComponent(
																								jTextFieldQuantidade,
																								GroupLayout.PREFERRED_SIZE,
																								GroupLayout.DEFAULT_SIZE,
																								GroupLayout.PREFERRED_SIZE)
																						.addGap(13)
																						.addComponent(
																								btnEscolherIngrediente))))
										.addPreferredGap(
												ComponentPlacement.RELATED)
										.addComponent(
												jButtonNovoProdutoComposto,
												GroupLayout.PREFERRED_SIZE, 79,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												ComponentPlacement.RELATED)
										.addComponent(jButtonVoltar)
										.addContainerGap(
												GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 6, Short.MAX_VALUE)));

		setModalityType(DEFAULT_MODALITY_TYPE);

		pack();
		setVisible(true);
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonNovoProdutoCompostoActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonNovoProdutoCompostoActionPerformed
		// pc = new ProdutoComposto(new
		// HashSet<Restaurante>().add(getContentPane().getParent()));

		Queue<Integer> quantidades_ingredientes = new LinkedList<Integer>();
		Set<ProdutoSimples> ingredientes = new HashSet<ProdutoSimples>();

		String nomeQuant;
		String nome;
		int quantidade;
		for (int i = 0; i < jListIngredientesQuantidade.getModel().getSize(); i++) {
			nomeQuant = jListIngredientesQuantidade.getModel().getElementAt(i)
					.toString();
			nome = nomeQuant.substring(1, nomeQuant.indexOf(','));
			quantidade = Integer.parseInt(nomeQuant.substring(
					nomeQuant.indexOf(',') + 2, nomeQuant.length() - 1));

			for (Produto ps : ProdutoSimples.allInstances()) {
				if (ps.nome().equals(nome)) {
					ingredientes.add((ProdutoSimples) ps);
					quantidades_ingredientes.add(quantidade);
				}
			}
		}

		iulChef_Cozinheiro.getEmpregado().CriarProdutoComposto(
				jTextFieldNome.getText(),
				(TipoProduto) jComboTipoProdutoComposto.getSelectedItem(),
				(Unidade) jComboBoxUnidade.getSelectedItem(),
				Double.parseDouble(jTextFieldPreco.getText()),
				Integer.parseInt(txtQtdComposto.getText()),
				quantidades_ingredientes,
				ingredientes,
				(GrupoProdutoComposto) jComboBoxGrupoProdutoComposto
						.getSelectedItem());
		
		new JOptionPane().showMessageDialog(this, "Novo produto criado com sucesso.");
	}// GEN-LAST:event_jButtonNovoProdutoCompostoActionPerformed

	private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonVoltarActionPerformed
		dispose();
	}// GEN-LAST:event_jButtonVoltarActionPerformed

	private void TipoProdutoCompostoActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_TipoProdutoCompostoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_TipoProdutoCompostoActionPerformed

	private void jComboBoxUnidadeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxUnidadeActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBoxUnidadeActionPerformed

	private void jComboBoxGrupoProdutoCompostoActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBoxGrupoProdutoCompostoActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBoxGrupoProdutoCompostoActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private ProdutoComposto pc;
	private javax.swing.JComboBox jComboTipoProdutoComposto;
	private javax.swing.JButton jButtonNovoProdutoComposto;
	private javax.swing.JButton jButtonVoltar;
	private javax.swing.JComboBox jComboBoxGrupoProdutoComposto;
	private javax.swing.JComboBox jComboBoxUnidade;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabelIngredientes;
	private javax.swing.JLabel jLabelNome;
	private javax.swing.JLabel jLabelPrecoVenda;
	private javax.swing.JLabel jLabelQuantidade;
	private javax.swing.JLabel jLabelQuantidadeIngredientes;
	private javax.swing.JLabel jLabelTipo;
	private javax.swing.JLabel jLabelUnidade;
	private javax.swing.JList jListIngredientes;
	private javax.swing.JList jListIngredientesQuantidade;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextField jTextFieldNome;
	private javax.swing.JTextField jTextFieldPreco;
	private javax.swing.JTextField jTextFieldQuantidade;
	private JTextField txtQtdComposto;
	private DefaultListModel model;
	private ArrayList<String> l = new ArrayList<String>();
}
