/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.quasar.IULChef.presentationLayer;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import org.quasar.IULChef.businessLayer.Empregado;
import org.quasar.IULChef.businessLayer.Entidade;
import org.quasar.IULChef.businessLayer.Restaurante;
import org.quasar.IULChef.persistenceLayer.Database;

/**
 *
 * @author terroma
 */
public class IULChef_Despedir extends javax.swing.JDialog {

	private Empregado empregado;
	private Restaurante restaurante;
	/**
	 * Creates new form IULChef_Despedir
	 * @param restaurante 
	 * @param empregado 
	 */
	public IULChef_Despedir(Empregado empregado, Restaurante restaurante) {
		this.empregado = empregado;
		this.restaurante = restaurante;
		initComponents();
		this.setTitle("Despedir");
		preencheComboBox();
		setModalityType(DEFAULT_MODALITY_TYPE);
		setLocation(550, 350);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabelEmpregado = new javax.swing.JLabel();
		jLabelNc = new javax.swing.JLabel();
		jButtonDespedir = new javax.swing.JButton();
		jButtonVoltar = new javax.swing.JButton();
		jComboBoxEmpregados = new javax.swing.JComboBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabelEmpregado.setText("Empregado");

		jLabelNc.setText("Nome/Nc:");

		jButtonDespedir.setText("Despedir");
		jButtonDespedir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonDespedirActionPerformed(evt);
			}
		});

		jButtonVoltar.setText("Voltar");
		jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonVoltarActionPerformed(evt);
			}
		});

		//        jComboBoxEmpregados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(jPanel1Layout.createSequentialGroup()
														.addContainerGap()
														.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(jButtonVoltar)
																.addComponent(jButtonDespedir, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addGroup(jPanel1Layout.createSequentialGroup()
																		.addGap(47, 47, 47)
																		.addComponent(jLabelEmpregado)))
																		.addGap(0, 0, Short.MAX_VALUE))
																		.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
																				.addGap(0, 0, Short.MAX_VALUE)
																				.addComponent(jLabelNc)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(jComboBoxEmpregados, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
																				.addContainerGap())
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabelEmpregado)
						.addGap(10, 10, 10)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jComboBoxEmpregados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelNc))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jButtonDespedir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButtonVoltar)
								.addGap(18, 18, 18))
				);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE))
				);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonDespedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDespedirActionPerformed
		Integer numeroEmpregados = Empregado.allInstances().size();
		Empregado empre = new Empregado();
		for (Entidade e : Empregado.allInstances()) {
			if(e.nome().equals(jComboBoxEmpregados.getSelectedItem())){
					empre = (Empregado) e;
			}
		}
		System.out.println(empre.toString());
		System.out.println(restaurante.toString());
		empregado.Despedir(restaurante, empre);
		
		if(numeroEmpregados<Empregado.allInstances().size()){
			JOptionPane.showMessageDialog(this, "O Empregado foi despedido com susseco!");
		}else{
			JOptionPane.showMessageDialog(this, "Nao foi possivel despedir o empregado!");
		}
		for(int i=0;i<jComboBoxEmpregados.getItemCount();i++){
	        jComboBoxEmpregados.removeItemAt(0);
	     }
		preencheComboBox();
	}//GEN-LAST:event_jButtonDespedirActionPerformed

	private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
		dispose();
	}//GEN-LAST:event_jButtonVoltarActionPerformed

	@SuppressWarnings("unchecked")
	private void preencheComboBox(){
		for (Entidade e : Empregado.allInstances()) {
			jComboBoxEmpregados.addItem(e.nome());
		}

	}//GEN-LAST:event

	public void setWindow(IULChef_Gerente iulChef_Gerente) {
		this.iulChefGerente = iulChef_Gerente;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonDespedir;
	private javax.swing.JButton jButtonVoltar;
	private javax.swing.JComboBox jComboBoxEmpregados;
	private javax.swing.JLabel jLabelEmpregado;
	private javax.swing.JLabel jLabelNc;
	private javax.swing.JPanel jPanel1;
	private IULChef_Gerente iulChefGerente;
	// End of variables declaration//GEN-END:variables
}
